# Generated by Django 4.2.13 on 2024-06-19 17:00

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lookbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "overlay_image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="overlay_images"
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("portrait", "Portrait"),
                            ("landscape", "Landscape"),
                            ("square", "Square"),
                        ],
                        default="square",
                        max_length=10,
                    ),
                ),
                ("border_width", models.CharField(default="0px", max_length=10)),
                ("border_color", models.CharField(default="black", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="profile_pictures"
                    ),
                ),
                (
                    "profile_url",
                    models.URLField(
                        blank=True,
                        default="https://res.cloudinary.com/yelenik/image/upload/v1717335704/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                        null=True,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "my_lookbooks",
                    models.ManyToManyField(blank=True, to="lookbook_app.lookbook"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LookbookImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="images"
                    ),
                ),
                ("transformed_image", models.URLField(blank=True, null=True)),
                (
                    "lookbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="lookbook_app.lookbook",
                    ),
                ),
            ],
        ),
    ]
